#include<stdio.h>
int main()
{
    int i,a,b=0,c,A[101],d=0,e=0,f=0,g=0;
    scanf("%d",&i);
    for(a=0;a<i;a++)
    {
       scanf("%d",&A[a]);
    }
    for(a=0;a<(i-1);a++)
    {
        if(A[i]<=A[i+1])
            c=A[i+1];
        else
            c=A[i];
    }
    for(a=0;a<(i-1);a++)
    {
        if(A[i]<=A[i+1])
            d=A[i];
        else
            d=A[i+1];
    }
    for(a=d;a<=c;a++)
    {
        for(b=0;b<i;b++)
        {
            e=e+(A[i]-d)*(A[i]-d);
        }
        for(b=0;b<i;b++)
        {
            f=f+(A[i+1]-d)*(A[i+1]-d);
        }
    if(e<=f)
    {
        g=e;
    }
    else
    {
        g=f;
    }
    }
printf("%d",g);
return 0;
}
